### ISSUE TITLE
...

### ISSUE THREAD

**Issue by thetechfnafexposer** [matpow2/anaconda#25]

**Comment by thetechfnafexposer** [comment]
And Autorek is innocent. He made a exe packer that removes the page header or something like that

**Comment by freddle1** [comment]
Yes... they have a way to decompile anything, and autorek's packer is easy to reverse. The subreddit turned to drama so I think it's time something has to be done about it. Adding a new compression format wouldn't help because they would just crack it... you need a way to keep games undecompileable...
